UPDATE public.ref
SET "NOTA_CANDIDATO" = TO_NUMBER(REPLACE("NOTA_CANDIDATO", ',', '.'), '9999999D99')
WHERE "NOTA_CANDIDATO" IS NOT NULL;

ALTER TABLE public.ref
ALTER COLUMN "NOTA_CANDIDATO" TYPE numeric USING ("NOTA_CANDIDATO"::numeric);



