
CREATE TABLE IF NOT EXISTS public.chamada_regular_2017_2
(
    "ANO" bigint,
    "EDICAO" bigint,
    "ETAPA" bigint,
    "DS_ETAPA" text COLLATE pg_catalog."default",
    "CODIGO_IES" bigint,
    "NOME_IES" text COLLATE pg_catalog."default",
    "SIGLA_IES" text COLLATE pg_catalog."default",
    "UF_IES" text COLLATE pg_catalog."default",
    "CODIGO_CAMPUS" bigint,
    "NOME_CAMPUS" text COLLATE pg_catalog."default",
    "UF_CAMPUS" text COLLATE pg_catalog."default",
    "MUNICIPIO_CAMPUS" text COLLATE pg_catalog."default",
    "CODIGO_CURSO" bigint,
    "NOME_CURSO" text COLLATE pg_catalog."default",
    "GRAU" text COLLATE pg_catalog."default",
    "TURNO" text COLLATE pg_catalog."default",
    "TIPO_MOD_CONCORRENCIA" text COLLATE pg_catalog."default",
    "MOD_CONCORRENCIA" text COLLATE pg_catalog."default",
    "PESO_L" text COLLATE pg_catalog."default",
    "PESO_CH" text COLLATE pg_catalog."default",
    "PESO_CN" text COLLATE pg_catalog."default",
    "PESO_M" text COLLATE pg_catalog."default",
    "PESO_R" text COLLATE pg_catalog."default",
    "NOTA_MINIMA_L" text COLLATE pg_catalog."default",
    "NOTA_MINIMA_CH" text COLLATE pg_catalog."default",
    "NOTA_MINIMA_CN" text COLLATE pg_catalog."default",
    "NOTA_MINIMA_M" text COLLATE pg_catalog."default",
    "NOTA_MINIMA_R" text COLLATE pg_catalog."default",
    "MEDIA_MINIMA" text COLLATE pg_catalog."default",
    "CPF" text COLLATE pg_catalog."default",
    "INSCRICAO_ENEM" text COLLATE pg_catalog."default",
    "INSCRITO" text COLLATE pg_catalog."default",
    "SEXO" text COLLATE pg_catalog."default",
    "DATA_NASCIMENTO" text COLLATE pg_catalog."default",
    "UF_CANDIDATO" text COLLATE pg_catalog."default",
    "MUNICIPIO_CANDIDATO" text COLLATE pg_catalog."default",
    "OPCAO" bigint,
    "NOTA_L" text COLLATE pg_catalog."default",
    "NOTA_CH" text COLLATE pg_catalog."default",
    "NOTA_CN" text COLLATE pg_catalog."default",
    "NOTA_M" text COLLATE pg_catalog."default",
    "NOTA_R" bigint,
    "NOTA_L_COM_PESO" text COLLATE pg_catalog."default",
    "NOTA_CH_COM_PESO" text COLLATE pg_catalog."default",
    "NOTA_CN_COM_PESO" text COLLATE pg_catalog."default",
    "NOTA_M_COM_PESO" text COLLATE pg_catalog."default",
    "NOTA_R_COM_PESO" bigint,
    "NOTA_CANDIDATO" text COLLATE pg_catalog."default",
    "NOTA_CORTE" text COLLATE pg_catalog."default",
    "CLASSIFICACAO" bigint,
    "APROVADO" text COLLATE pg_catalog."default",
    "MATRICULA" text COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.chamada_regular_2017_2
    OWNER to postgres;