select "ANO", "CODIGO_CURSO", "NOME_CURSO",  count(*) as "INSCRITOS" 
from (
select distinct on 
	("INSCRITO", "INSCRICAO_ENEM", "DATA_NASCIMENTO", "CODIGO_CURSO")
	"ANO", "CODIGO_CURSO", "NOME_CURSO"
	from chamada_regular_2022_1
	)
group by "ANO", "CODIGO_CURSO", "NOME_CURSO"


SELECT "ANO", "CODIGO_CURSO", "NOME_CURSO", "MUNICIPIO_CAMPUS", "UF_CAMPUS", count(*) as "QTD_INSCRITOS"
from (select distinct on 
	("INSCRITO", "INSCRICAO_ENEM", "DATA_NASCIMENTO", "CODIGO_CURSO", "MUNICIPIO_CAMPUS")
	"ANO", "CODIGO_CURSO", "NOME_CURSO", "MUNICIPIO_CAMPUS","UF_CAMPUS"
	from chamada_regular_2022_1)
group by "ANO", "CODIGO_CURSO", "NOME_CURSO", "MUNICIPIO_CAMPUS" ,"UF_CAMPUS"